name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip files
        run: |
          cd 1.16.5/FPP
          zip -qq -r FPP-$(echo ${{ github.sha }} | cut -c1-7)-1.16.5.zip *

      - uses: actions/upload-artifact@v4
        with:
          name: FPP-1.16.5-unzip2use
          path: 1.16.5/FPP/FPP-*
