name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a /FPP-$(echo ${{ github.sha }} | cut -c1-7).zip -r "/1.16.5/FPP"
      - uses: actions/upload-artifact@v4
        with:
          name: Upload zip
          path: FPP-*
