name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
        with:
          args: zip -q -r FPP.zip "/1.16.5/FPP"
      - name: pack
        run: mv FPP.zip FPP-$(echo ${{ github.sha }} | cut -c1-7).zip 
      - uses: actions/upload-artifact@v4
        with:
          name: Upload zip
          path: FPP-*
