name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pack
        run: 	zip -r /FPP-$(echo ${{ github.sha }} | cut -c1-7).zip /1.16.5/FPP
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: Upload zip
          path: FPP-*
